# Generated by Django 5.1.4 on 2025-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=1, upload_to='faces/'),
            preserve_default=False,
        ),
    ]
